import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'

import ReactQueryClientProvider from 'components/ReactQueryClientProvider'

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Boilerplate Next 14',
  description: 'Generated by create next app',
  generator: 'Next.js',
  manifest: '/manifest.json',
  authors: [
    {
      name: 'Charles Randicha Gunawan Santoso',
      url: 'https://randicha.dev',
    },
  ],
  icons: [
    {
      rel: 'apple-touch-icon',
      url: 'images/icons/icon-128x128.png',
    },
    {
      rel: 'icon',
      url: 'images/icons/icon-128x128.png',
    },
  ],
}

export const viewport: Viewport = {
  themeColor: '#ffffff',
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  userScalable: true,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  )
}
