import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'

import ReactQueryClientProvider from 'components/ReactQueryClientProvider'

import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

const ICONS_SIZES = [72, 96, 128, 144, 152, 192, 384, 512]

export const metadata: Metadata = {
  title: 'Boilerplate Next 14',
  description: 'Generated by create next app',
  generator: 'Next.js',
  manifest: '/manifest.json',
  authors: [
    {
      name: 'Charles Randicha Gunawan Santoso',
      url: 'https://randicha.dev',
    },
  ],
  icons: [
    ...ICONS_SIZES.map((size) => ({
      url: `/images/icons/icon-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      rel: 'apple-touch-icon',
    })),
    ...ICONS_SIZES.map((size) => ({
      url: `/images/icons/icon-${size}x${size}.png`,
      sizes: `${size}x${size}`,
      rel: 'icon',
      type: 'image/png',
    })),
  ],
  robots: 'index, follow',
  // this disables the error about openGraph metadatabase using localhost:3000
  ...(process.env.NODE_ENV === 'production' && {
    openGraph: {
      type: 'website',
      title: 'Boilerplate Next 14',
      description: 'Generated by create next app',
      siteName: 'Boilerplate Next 14',
      url: process.env.NEXT_PUBLIC_BASE_URL,
      images: [
        {
          url: '/images/icons/icon-384x384.png',
          width: 384,
          height: 384,
          alt: 'Boilerplate Next 14',
        },
      ],
    },
  }),
}

export const viewport: Viewport = {
  themeColor: '#ffffff',
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
  userScalable: true,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  )
}
